### ISSUE TITLE
[BUG] An issue occurred while setting up your wallet for signing. You've been signed out. If the issue persists, contact support.

### ISSUE THREAD

**Issue by T3knoLogic** [dfinity/oisy-wallet#3390] opened 2024-11-07 04:10 UTC
**Describe the bug**
While logging in, I get directed to Internet Identity and that verifies successfully but I receive the error "An issue occurred while setting up your wallet for signing. You've been signed out. If the issue persists, contact support"

I have logged in, deposited tokens, and used Oisy dozens of times successfully but now appear to be locked out of it.

I log into NNS successfully so this is very weird. A bit bummed my tokens are inaccessible.
![IMG_4095](https://github.com/user-attachments/assets/c273d5cb-bea3-4045-9f1f-2b97ed40ea97)
![IMG_4094](https://github.com/user-attachments/assets/0c2719da-6684-4a09-8c58-a6d03c375778)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: iOS Windows 11
- Browser [chrome, safari, brave]
- Version Latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by peterpeterparker** [comment] 2024-11-07 05:23
Hi, I can reproduce the issue as well. I was able to narrow it down, but I’m not sure what the exact issue is yet. I’ve shared the details with the team. It’s 6am here, so it might take a few hours to resolve. We’ll keep you posted.

**Comment by T3knoLogic** [comment] 2024-11-07 05:26
Amazing! Thank you so much! 🫶

**Comment by peterpeterparker** [comment] 2024-11-07 07:58
Issue resolved ✅. The backend canister ran out of funds on the Cycles ledger, which in turn caused the sign-in process to fail when attempting to allow signing on the Signer canister. To prevent this from happening again in the future, we will develop some automation.

I'm closing this issue as the problem is resolved, and the automation is tracked internally separately.

**Closed by peterpeterparker** 2024-11-07 07:58 UTC
Labels: bug
